# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-03 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absence',
            },
        ),
        migrations.CreateModel(
            name='Coursework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursework', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Coursework',
                'verbose_name_plural': 'Courseworks',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Group')),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab', models.CharField(blank=True, default='', max_length=3, null=True, verbose_name='Subject')),
            ],
            options={
                'verbose_name': 'Lab',
                'verbose_name_plural': 'Labs',
            },
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Subject')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mystudents.Group')),
                ('lab', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mystudents.Lab')),
            ],
            options={
                'verbose_name': 'Progress',
                'verbose_name_plural': 'Progress',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Semester')),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Last name')),
                ('name', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Name')),
                ('patronym', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Patronym')),
                ('tel', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Telephon number')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mystudents.Group')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Subject')),
                ('group', models.ManyToManyField(blank=True, null=True, to='mystudents.Group')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Subject_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(blank=True, default='', max_length=25, null=True, verbose_name='Subject type')),
            ],
            options={
                'verbose_name': 'Subject type',
                'verbose_name_plural': 'Subject types',
            },
        ),
        migrations.AddField(
            model_name='progress',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mystudents.Semester'),
        ),
        migrations.AddField(
            model_name='progress',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mystudents.Student'),
        ),
        migrations.AddField(
            model_name='lab',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mystudents.Subject'),
        ),
        migrations.AddField(
            model_name='coursework',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mystudents.Semester'),
        ),
        migrations.AddField(
            model_name='coursework',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mystudents.Student'),
        ),
        migrations.AddField(
            model_name='coursework',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mystudents.Subject'),
        ),
        migrations.AddField(
            model_name='absence',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mystudents.Group'),
        ),
        migrations.AddField(
            model_name='absence',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mystudents.Semester'),
        ),
        migrations.AddField(
            model_name='absence',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mystudents.Student'),
        ),
        migrations.AddField(
            model_name='absence',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mystudents.Subject'),
        ),
        migrations.AddField(
            model_name='absence',
            name='subject_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mystudents.Subject_type'),
        ),
    ]
